export const devMock = {
    "_id": {
        "$oid": "672ce20ef9728ef4f790756e"
    },
    "id": "1730994702271",
    "centerLetter": "a",
    "pangrams": [
        "allotropy"
    ],
    "letters": [
        "a",
        "l",
        "o",
        "t",
        "r",
        "p",
        "y"
    ],
    "validWords": [
        "allay",
        "allot",
        "allotropy",
        "allyl",
        "altar",
        "aorta",
        "aport",
        "appall",
        "apparat",
        "apply",
        "appro",
        "aptly",
        "arroyo",
        "aryl",
        "atlatl",
        "atoll",
        "atopy",
        "attar",
        "lota",
        "loyal",
        "loyalty",
        "lyart",
        "olla",
        "opal",
        "orally",
        "orator",
        "palatal",
        "pallor",
        "pally",
        "paltry",
        "paly",
        "papa",
        "papal",
        "papaya",
        "pappy",
        "parol",
        "parr",
        "parry",
        "partly",
        "patty",
        "payola",
        "payroll",
        "poplar",
        "poppa",
        "portray",
        "portrayal",
        "potato",
        "prat",
        "pray",
        "proa",
        "prototypal",
        "pyrola",
        "rapport",
        "rapt",
        "raptor",
        "rattly",
        "rattrap",
        "ratty",
        "rota",
        "rotator",
        "rotatory",
        "royally",
        "royalty",
        "tall",
        "taproot",
        "taro",
        "tarot",
        "tarp",
        "tarty",
        "tatty",
        "tola",
        "tolar",
        "torta",
        "totally",
        "tray",
        "typal"
    ],
    "__v": 0
};
